# Form implementation generated from reading ui file 'window_copy_excel.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadingPage(object):
    def setupUi(self, LoadingPage):
        LoadingPage.setObjectName("LoadingPage")
        LoadingPage.resize(520, 350)
        LoadingPage.setMinimumSize(QtCore.QSize(520, 350))
        LoadingPage.setMaximumSize(QtCore.QSize(520, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        LoadingPage.setWindowIcon(icon)
        LoadingPage.setStyleSheet("background: #A2AEFF")
        self.label_title = QtWidgets.QLabel(parent=LoadingPage)
        self.label_title.setGeometry(QtCore.QRect(30, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.list_widget = QtWidgets.QListWidget(parent=LoadingPage)
        self.list_widget.setGeometry(QtCore.QRect(0, 80, 521, 261))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setItalic(False)
        self.list_widget.setFont(font)
        self.list_widget.setStyleSheet("padding-left: 5px; background: #cfd2ff")
        self.list_widget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.list_widget.setProperty("isWrapping", True)
        self.list_widget.setUniformItemSizes(False)
        self.list_widget.setWordWrap(True)
        self.list_widget.setObjectName("list_widget")
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        self.btn_load = QtWidgets.QPushButton(parent=LoadingPage)
        self.btn_load.setGeometry(QtCore.QRect(370, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.btn_load.setFont(font)
        self.btn_load.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WhatsThisCursor))
        self.btn_load.setStyleSheet("background: rgb(225, 232, 255);")
        self.btn_load.setAutoDefault(False)
        self.btn_load.setObjectName("btn_load")

        self.retranslateUi(LoadingPage)
        QtCore.QMetaObject.connectSlotsByName(LoadingPage)

    def retranslateUi(self, LoadingPage):
        _translate = QtCore.QCoreApplication.translate
        LoadingPage.setWindowTitle(_translate("LoadingPage", "Копирование и сохранение листа из excel-файла"))
        self.label_title.setText(_translate("LoadingPage", "Инструкция:"))
        __sortingEnabled = self.list_widget.isSortingEnabled()
        self.list_widget.setSortingEnabled(False)
        item = self.list_widget.item(1)
        item.setText(_translate("LoadingPage", "1. Перед закрытием информационной справки - оставьте активным лист, который Вам необходимо скопировать;"))
        item = self.list_widget.item(3)
        item.setText(_translate("LoadingPage", "2. Создайте пустой файл-excel с одним листом;"))
        item = self.list_widget.item(5)
        item.setText(_translate("LoadingPage", "3. Выберите информационную справку откуда будет копироваться лист;"))
        item = self.list_widget.item(7)
        item.setText(_translate("LoadingPage", "4. Выберите файл куда будет сохранена копия текущего дня (если происходит перезапись информации в файле, где уже имеется заполненный лист, Вам необходимо подтвердить - УДАЛЕНИЕ информации. Информация будет обновлена)."))
        self.list_widget.setSortingEnabled(__sortingEnabled)
        self.btn_load.setToolTip(_translate("LoadingPage", "выбрать файл"))
        self.btn_load.setText(_translate("LoadingPage", "Загрузить файл"))
